version: '3.8'

services:
  web:
    image: ${DOCKER_REGISTRY_USER}/tea-house-api:${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy  # Ensures db health check passes first

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER} #tea_user
      - POSTGRES_PASSWORD=${DB_PASSWORD} #tea_password
      - POSTGRES_DB=${DB_NAME} #tea_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tea_user -d tea_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: