---
- name: Deploy Microservices to EKS Cluster
  hosts: localhost
  vars_files:
    - secrets.yml # <-- Load the encrypted file
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure RabbitMQ broker is deployed
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../k8s-manifests/rabbitmq.yaml') }}"

    - name: Wait for RabbitMQ to become operational
      kubernetes.core.k8s_info:
        kind: Deployment
        name: rabbitmq
        namespace: default
      register: rabbitmq_status
      until: "rabbitmq_status.resources[0].status.readyReplicas | default(0) == 1"
      retries: 10
      delay: 10

    - name: Deploy FastAPI Gateway Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../k8s-manifests/api-service.yaml') }}"

    - name: Deploy DB Worker Daemon
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../k8s-manifests/db-worker-service.yaml') }}"
    # ... (Your existing tasks for RabbitMQ and the API) ...

    - name: Add Prometheus Community Helm Repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy kube-prometheus-stack via Helm
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: default
        create_namespace: true
        state: present
        wait: true
        # We disable some heavy default components to save EKS resources
        values:
          alertmanager:
            enabled: false
          grafana:
            adminPassword: "{{ vault_grafana_password }}"

    - name: Apply API ServiceMonitor for Prometheus scraping
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s/api-servicemonitor.yaml') }}"