apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-container
        image: dev-boops.dkr.ecr.ap-south-1.amazonaws.com/tea-house-api:latest
        ports:
        - containerPort: 8000
          name: http-metrics # Required for Prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31456 
    name: http-metrics # Must match the container port name
  selector:
    app: api-gateway